const CountryContinentData = {
  Europe: [
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Portugal",
    "Greece",
    "England",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Switzerland",
  ],
  Asia: [
    "China",
    "Japan",
    "India",
    "South Korea",
    "Thailand",
    "Vietnam",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "Singapore",
    "Malaysia",
    "Hong Kong",
    "Taiwan",
    "Hong Kong",
    "Taiwan",
  ],
  Africa: [
    "Nigeria",
    "Egypt",
    "South Africa",
    "Kenya",
    "Morocco",
    "Algeria",
    "Tunisia",
    "Angola",
    "Zimbabwe",
    "Zambia",
    "Madagascar",
    "Mozambique",
  ],
  America: [
    "United States",
    "Canada",
    "Mexico",
    "Brazil",
    "Argentina",
    "Chile",
    "Peru",
    "Colombia",
    "Venezuela",
    "Ecuador",
    "Bolivia",
  ],
  Australia: [
    "Australia",
    "New Zealand",
    "Fiji",
    "Papua New Guinea",
    "Solomon Islands",
    "Vanuatu",
    "New Caledonia",
    "Samoa",
    "Tonga",
    "Fiji",
    "New Caledonia",
  ],
} as const;

export type CountryContinent = keyof typeof CountryContinentData | "All";

export const CountryContinentMap: Record<CountryContinent, readonly string[]> =
  {
    All: Object.values(CountryContinentData).flatMap((country) => country),
    Europe: CountryContinentData.Europe,
    Asia: CountryContinentData.Asia,
    Africa: CountryContinentData.Africa,
    America: CountryContinentData.America,
    Australia: CountryContinentData.Australia,
  };
